### ISSUE TITLE
Searching can sometimes leave stale python processes running

### ISSUE THREAD

**Issue by rhydlewis** [rhydlewis/search-omnifocus#1]
* In Alfred, type:

    .s e

* Alfred says "Searching..."
* In terminal, type:

     ps aux | grep python

to see:

    python search.py e

still running.

Note, running python script from workflow folder works. Alfred debug log doesn't seem to show anything happening. Odd.

**Comment by deanishe** [comment]
It's probably [this issue with a lot of output on STDERR](https://github.com/deanishe/alfred-workflow/issues/80#issuecomment-198127526).

Fixed in latest versions of Alfred-Workflow and Alfred.

**Comment by rhydlewis** [comment]
Fixe

**Comment by deanishe** [comment]
Was that the problem?

**Comment by rhydlewis** [comment]
@deanishe Think so - updated the workflow folder with the latest release and I can't recreate it. Thanks for the fix.

**Comment by deanishe** [comment]
@fniephaus found the bug and Andrew fixed it, tbf. That fix unbroke a lot of workflows.
