### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Reagy30** [rhydlewis/search-omnifocus#11]
Hi there, I noticed it's no longer working on El Capitan. Is it just an isolated issue with mine?

**Comment by rhydlewis** [comment]
Hi, works for me on El Capitan 10.11 (15A284). What's not working? You can send me debug logs by doing this:

* Show Alfred preferences (keyword 'alf')
* Click 'Workflows' in the tool bar
* Choose 'Search Omnifocus' from the list of workflows on the left
* Click on the 'Debug' to toggle debugging mode (see [Alfred's help page for more info](https://www.alfredapp.com/help/workflows/advanced/debugger/))
* Choose 'All information' from the Log dropdown
* Open Alfred and type the query that's not working
* Copy the debug output and post it as a response - I'll take a look.

Cheers

**Comment by deanishe** [comment]
I had a similar issue. After resetting the workflow (`.s workflow:reset`), it worked again just dandy.

**Comment by Reagy30** [comment]
Hi Rhyd,

It’s finally working now, thank you. Sorry for the inconvenience!


Best regards

Reg

**Comment by Reagy30** [comment]
Thank you for the advice. It’s working fine for me now but I didn’t do a reset. Just re-downloaded Alfred and restarted my Mac.
