### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by nicktanderson** [rhydlewis/search-omnifocus#12]
![screen shot 2015-10-27 at 11 37 37 am](https://cloud.githubusercontent.com/assets/15345872/10763142/2aee4602-7c9f-11e5-908d-e6f0a786695b.png)

I get the above results when trying to use this workflow. I have looked through the readme and can't find any additional installation instruction about adding specific database info. Any suggestions?

**Comment by rhydlewis** [comment]
Hi, the workflow looks for the Omnifocus database in 1 of 2 locations:

1. the default location if you purchased Omnifocus from OmniGroup directly `~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2`
2. an alternative location if you purchased from the Mac AppStore `~/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2`

Can you run the following in Terminal.app and post the output back?

	ls -l ~/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2
	ls -l ~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2

For me, the results show I have the Mac AppStore version:

	> ls -l ~/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2
	-rw-r--r--@ 1 uname  staff  1036288 27 Oct 14:38 /Users/uname/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2

	> ls -l ~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2
	ls: /Users/uname/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2: No such file or directory

**Comment by nicktanderson** [comment]
ls:
/Users/nicktanderson/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2:
No such file or directory

NickMacPro:~ nicktanderson$ ls -l
~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2

ls:
/Users/nicktanderson/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2:
No such file or directory

NickMacPro:~ nicktanderson$


¡

Nick T. Anderson
Post Production Specialist
www.nicktanderson.com

**Comment by rhydlewis** [comment]
Hmmm. Which version of Omnifocus are you running? I'm running v2.3.

**Comment by nicktanderson** [comment]
I was on a 2.2 version. Just updated and now it works like a charm. Thanks!

Nick T. Anderson
Post Production Specialist
www.nicktanderson.com

**Comment by alehandrof** [comment]
I'm getting the same issue with "Search Omnifocus" v.1.1.15 and Omnifcous 2.6.2. It started happening when I update the workflow from v.1.1.11 (the version in Packal). My database is at `~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2`.

**Comment by macfreek** [comment]
@alehandrof I had the same problem and opened a new ticket, #20. Since the above is a year old, this may be a newer (albeit related) problem.
