### ISSUE TITLE
Idea: .r for recently changed items

### ISSUE THREAD

**Issue by askedrelic** [rhydlewis/search-omnifocus#14]
Occasionally I'll create a quick todo in the inbox, but then quickly change my mind.

You should be able to get a list of recently changed items, right? Being able to quickly get a list of your last changed items would be nice, to quickly jump back to something.

**Comment by rhydlewis** [comment]
Not a bad idea - I'll look at adding this in future. Thanks.

**Comment by rhydlewis** [comment]
Hi - almost a year later... does this do the trick?

https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.1.18

**Comment by askedrelic** [comment]
Awesome, thanks for taking a look at this! I'm still using workflow daily...

It works for me! It looks like in the code you are ignoring tasks modified in the inbox specifically? I'm only seeing recent tasks that are in projects. I would think "recent" would include those tasks; "I just created a task, either in a project or the inbox, where is it?" Does that make sense?

I also don't understand the alfred param format for ".r". I changed it to "argument optional" and the usage makes more sense to me: https://files.asktherelic.com/20161123-1500-yttis.png

So ".r" in alfred shows my 10 recent tasks? I would think it should work more like ".i" to get a list of all inbox items and then ".r <filter words>" to filter. I guess changing how many recent items I see doesn't seem like something I would usually do.

**Comment by rhydlewis** [comment]
I've changed the behaviour so that it shows the last 10 modified tasks or projects irrespective of location. I'm going to keep it simple so that `.r` shows all recently modified and `.ra` shows recently modified and not completed items.

Update in a day or so to come.

**Comment by rhydlewis** [comment]
Recent item support added in [v1.2.2](https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.2.2).

Cheers

**Comment by askedrelic** [comment]
Thanks again, those tweaks make sense to me! Great to see this get added :)
