### ISSUE TITLE
.v & .lv not working if some perspectives start with a emoji

### ISSUE THREAD

**Issue by henryfish** [rhydlewis/search-omnifocus#16]
I have some perspectives starting with a emoji, such as 🔬 or 💻. .v & .lv returns "'acsii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)"

**Comment by rhydlewis** [comment]
Fixed in [v1.1.13](https://github.com/rhydlewis/search-omnifocus/releases/download/v1.1.13/Search.OmniFocus.v1.1.13.alfredworkflow)
