### ISSUE TITLE
Better Icon?

### ISSUE THREAD

**Issue by dannysmith** [rhydlewis/search-omnifocus#17]
Thanks for building this - it's awesome.

I just threw together a new icon for me to use and thought you might want to use it too (by 'threw together", I actually mean "drew a glass on top of the OF logo"). It seemed silly to fork and PR for this, but I can if you want to use it.

![slice 1](https://cloud.githubusercontent.com/assets/28115/13545373/26d04456-e281-11e5-92cb-22b0574ff8f2.png)

**Comment by rhydlewis** [comment]
Awesome! Thanks - I've updated the workflow today with this new icon. Nice one.

**Comment by timbroder** [comment]
Awesome!! Thank you @dannysmith!!

**Comment by dannysmith** [comment]
No problem 👍
