### ISSUE TITLE
.ff for focus on folder

### ISSUE THREAD

**Issue by JacqLAB** [rhydlewis/search-omnifocus#18]
Hi, 
- OmniFocus users using perspectives to filter and display tasks may end up with lists longer than one screen. Having folders to separate groups of projects help to reduce the clutter by focusing on a folder but, you have first to focus on the folder before the perspective selection. 
- It would be pretty useful to have a variant of the .f command. 
  - In place of opening the folder, a .ff (focus on folder) would instantly limit the currently displayed tasks to the folder scope. 
  - One could also use the command modifier to modify the .f to focus in  place of opening?

---

I simply and successfully modified the ".f script filter" in the workflow. I added a "run NSAppleScript action" connected to the script filer ".f"  through the "command modifier". The script is as follows:

```
on alfred_script(q)
  tell application "OmniFocus" to tell the default document
    set folderList to flattened folders whose id is q
    tell the front document window to set focus to folderList
    activate
  end tell
end alfred_script 
```

**Comment by rhydlewis** [comment]
hi - thanks for the feedback. I'll add this to the backlog for the workflow.

**Comment by rhydlewis** [comment]
Focusing on folders supported in v1.2.7 - cheers! (2 years since the request - wow... 😱)

https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.2.7

**Comment by JacqLAB** [comment]
Hi,


> Le 19 avr. 2018 à 09:16, Rhyd Lewis <notifications@github.com <mailto:notifications@github.com>> a écrit :
> 
> Focusing on folders supported in v1.2.7 - cheers! (2 years since the request - wow... 😱)
> 
> 

Long maturation, better fruits :)

Thanks,

Thierry
