### ISSUE TITLE
Post .workflow file for v1.1.1

### ISSUE THREAD

**Issue by alexlafroscia** [rhydlewis/search-omnifocus#2]
Can you please post the `.workflow` file for the latest release?

**Comment by rhydlewis** [comment]
Updated. Sorry about that. GitHub rejected the .alfredworkflow file as 'unsupported'. Weird. Uploaded now as [a zip](https://github.com/rhydlewis/search-omnifocus/releases/download/v1.1.1/Search.OmniFocus.v1.1.1.alfredworkflow.zip)

**Comment by rhydlewis** [comment]
[Workflow file](https://github.com/rhydlewis/search-omnifocus/releases/download/v1.1.1/Search.OmniFocus.v1.1.1.alfredworkflow) updated - not sure what happened there...

**Comment by alexlafroscia** [comment]
Thanks!
