### ISSUE TITLE
Database not found

### ISSUE THREAD

**Issue by macfreek** [rhydlewis/search-omnifocus#20]
I just installed the Omnifocus workflow for Alfred. Unfortunately, it can't find the database.

This may or may not be related to issue #12.

I'm running Alfred 3.1, and OmniFocus 2.6.2.

The database is in fact in `/Users/freek/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2`. (The non-MAS location). Looking at the code, I see that it looks in two locations. Why it has not found it, I don't know yet.

Let me know if there is a particular way to debug this.

```
[2016-09-06 08:31:08][ERROR: input.scriptfilter] Code 1: 08:31:08 workflow.py:1972 DEBUG    Workflow version : 1.1.11
08:31:08 workflow.py:1387 DEBUG    Reading settings from `/Users/freek/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json` ...
08:31:08 workflow.py:2233 DEBUG    Update check not due
08:31:08 search.py:36 DEBUG    Started workflow
08:31:08 search.py:133 DEBUG    [u'freek']
08:31:08 workflow.py:1610 DEBUG    Loading cached data from : /Users/freek/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/__workflow_update_status.cpickle
08:31:08 workflow.py:2181 DEBUG    update_data : {u'available': True, u'version': u'v1.1.15', u'download_url': u'https://github.com/rhydlewis/search-omnifocus/releases/download/v1.1.15/Search.OmniFocus.v1.1.15.alfredworkflow'}
08:31:08 search.py:118 DEBUG    Searching tasks
08:31:08 workflow.py:1511 DEBUG    Data `db_path` stored in `cpickle` format
08:31:08 workflow.py:1526 DEBUG    Stored data loaded from : /Users/freek/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/db_path.cpickle
08:31:08 search.py:169 DEBUG    /Users/freek/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2
08:31:08 workflow.py:1990 ERROR    unable to open database file
Traceback (most recent call last):
  File "/Users/freek/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.94461B96-1AB4-4831-8683-286AFDA280C2/workflow/workflow.py", line 1983, in run
    func(self)
  File "search.py", line 47, in main
    get_results(sql, args.type)
  File "search.py", line 55, in get_results
    results = run_query(sql)
  File "search.py", line 171, in run_query
    conn = sqlite3.connect(db_path)
OperationalError: unable to open database file
08:31:08 workflow.py:2008 DEBUG    Workflow finished in 0.104 seconds.
```

**Comment by timbroder** [comment]
Just a thought, but they just added client side encryption. Not sure if that's related

**Comment by deanishe** [comment]
Try deleting this file then run the workflow again:

```
/Users/freek/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/db_path.cpickle
```

**Comment by alehandrof** [comment]
I don't have a `~/Library/Application Support/Alfred 3/Workflow Data` folder at all.

**Comment by rhydlewis** [comment]
@timbroder don't think it's this as the locations haven't - to my knowledge - changed as part of the encryption changes but thanks for the suggestion

**Comment by rhydlewis** [comment]
@macfreek @alehandrof can you confirm which version of the workflow you're using please?

1. Open Alfred preferences and right click on the Search Omnifocus workflow
2. Choose Open in Finder
3. Open the file called 'version'
4. If you don't see 1.1.15 then please upgrade to the latest version (https://github.com/rhydlewis/search-omnifocus/releases/download/v1.1.15/Search.OmniFocus.v1.1.15.alfredworkflow)

@macfreek in your case, I'm wondering if the db_path.cpickle file has an incorrect or empty reference to the Omnifocus database. Suggestion from @deanishe to delete the file should help here.

@alehandrof, do you see the same issue as @macfreek? Can you post the debug information from Alfred?

**Comment by rhydlewis** [comment]
@alehandrof sorry, didn't spot that you already commented about the version number in #12. Please post the debug log to help me investigate. Thanks

**Comment by macfreek** [comment]
Thanks, @deanishe, your suggestion works. The file did indeed contain a path referencing the MAS location. (I did a quick strings of the file).

I'm running version 1.1.11 of the workflow, as that was the latest I found at http://www.packal.org/workflow/search-omnifocus. I'll update to the Github version in a moment.

A quick check revealed that the workflow file I installed did not originally contain a db_path.cpickle file. This means it was created on my Mac. What I suspect happened is as follows: when I first used this workflow, OmniFocus 2 was not installed (my trigger to buy the upgrade from OF 1 to OF 2 was triggered that it was not supported by this workflow). Apparently, when no valid path is found, search.py created a pickle file with the MAS path.

Regardless of what's in the cpickle file, I expect search.py to ignore (or recreate) the db_path.cpickle file, if it's content is invalid, because the file can't be found.

**Comment by rhydlewis** [comment]
Thanks for letting me know that Packal is out of date. I've updated it now.

**Comment by alehandrof** [comment]
@rhydlewis Here's the debug log:

```
10:23:54 workflow.py:2154 DEBUG    Workflow version : 1.1.15
10:23:54 workflow.py:1556 DEBUG    Reading settings from `/Users/alex/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json` ...
10:23:54 workflow.py:2176 ERROR    No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.B3CEB625-348A-4E66-AD72-D2D34E1E671C/workflow/workflow.py", line 2166, in run
    self.check_update()
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.B3CEB625-348A-4E66-AD72-D2D34E1E671C/workflow/workflow.py", line 2414, in check_update
    if not force and not self.settings.get('__workflow_autoupdate', True):
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.B3CEB625-348A-4E66-AD72-D2D34E1E671C/workflow/workflow.py", line 1558, in settings
    self._default_settings)
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.B3CEB625-348A-4E66-AD72-D2D34E1E671C/workflow/workflow.py", line 974, in __init__
    self._load()
  File "/Users/alex/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.B3CEB625-348A-4E66-AD72-D2D34E1E671C/workflow/workflow.py", line 986, in _load
    for key, value in json.load(file_obj, encoding='utf-8').items():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
10:23:54 workflow.py:2197 DEBUG    Workflow finished in 0.036 seconds.
```

**Comment by rhydlewis** [comment]
@alehandrof if you type this command (note, should be all on 1 line) into Terminal.app what does it show you?

`cat /Users/alex/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json`

My file shows:

`{`
  `"__workflow_last_version": "1.1.15"`
`}`

If you don't see that, try deleting the `settings.json` file to see if that forces the workflow to recreate it. @deanishe do you know what might be causing this?

**Comment by alehandrof** [comment]
@rhydlewis that was it! The `settings.json` was there, but it was empty. After I deleted it the workflow now works again!

**Comment by rhydlewis** [comment]
Whoop whoop! Glad it's working now.

**Comment by counterbeing** [comment]
Just wanted to chime in and say that deleting the `cpickle` file did the trick for me immediately. Thank you @deanishe!

Copy paste-able for anyone else:
```rm ~/Library/Application\ Support/Alfred\ 3/Workflow\ Data/net.rhydlewis.alfred.searchomnifocus/db_path.cpickle```
