### ISSUE TITLE
Tasks in inbox are not always found

### ISSUE THREAD

**Issue by macfreek** [rhydlewis/search-omnifocus#21]
I've noticed that search-omnifocus does not find all tasks. I had the impression it did not find newer items in the inbox. After a bit debugging, it seems that search-omnifocus runs the following query:

`cd ~/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2`
`sqlite3 OmniFocusDatabase2 SELECT t.persistentIdentifier, t.name, t.dateCompleted, t.blockedByFutureStartDate, c.name, p.name, t.flagged, t.dateToStart, t.inInbox, t.effectiveInInbox, t.effectiveDateToStart, t.childrenCountAvailable, t.blocked, pi.status, t.effectiveFlagged, t.dateModified, t.containingProjectInfo FROM ((task tt left join projectinfo pi on tt.containingprojectinfo=pi.pk) t left join task p on t.task=p.persistentIdentifier) left join context c on t.context = c.persistentIdentifier WHERE lower(t.name) LIKE lower('%query%') AND t.dateCompleted IS NULL AND t.containingProjectInfo <> t.persistentIdentifier ORDER BY t.name ASC`

I could resolve this problem by removing the part `AND t.containingProjectInfo <> t.persistentIdentifier` from the query. In that case, new tasks in the Inbox are found too.

I run the query on some sample data, and got this result:

|t.containingProjectInfo|t.persistentIdentifier|t.name|c.name|p.name|t.inInbox|t.blocked|pi.status|
|-----------------------|----------------------|------|------|------|---------|---------|---------|
|brCwH7ATZfq|brCwH7ATZfq|Search-omnifocus project||Search-omnifocus project|0|1|active|
|brCwH7ATZfq|n2o7OKloiCc|search-omnifocus group of tasks||Search-omnifocus project|0|1|active|
||kSqW6_0Fod8|search-omnifocus in inbox, no project or context|||1|0||
||hTVJT1AKEjJ|search-omnifocus in inbox, project and context|||1|0||
||gXj1JOu9LJx|search-omnifocus in inbox, project, no context|||1|0||
|oOivpkdUhPX|gaIYqG87cY8|search-omnifocus with project and context|Offline|Bug Report|0|0|active|
|oOivpkdUhPX|n6jvdmfMr3O|search-omnifocus with project and no context||Bug Report|0|0|active|

It seems that this part of the query is ment to prevent names of projects to be found. Unfortunately `t.containingProjectInfo <> t.persistentIdentifier` also seems to be false if `t.containingProjectInfo` is NULL and `t.persistentIdentifier` is not. One way to solve this is to change this part of the query to `(t.containingProjectInfo <> t.persistentIdentifier OR t.containingProjectInfo IS NULL)`:

`sqlite3 OmniFocusDatabase2 "SELECT t.persistentIdentifier, t.name, t.dateCompleted, t.blockedByFutureStartDate, c.name, p.name, t.flagged, t.dateToStart, t.inInbox, t.effectiveInInbox, t.effectiveDateToStart, t.childrenCountAvailable, t.blocked, pi.status, t.effectiveFlagged, t.dateModified, t.containingProjectInfo FROM ((task tt left join projectinfo pi on tt.containingprojectinfo=pi.pk) t left join task p on t.task=p.persistentIdentifier) left join context c on t.context = c.persistentIdentifier WHERE lower(t.name) LIKE lower('%query%') AND t.dateCompleted IS NULL AND (t.containingProjectInfo <> t.persistentIdentifier OR t.containingProjectInfo IS NULL) ORDER BY t.name ASC`

**Comment by rhydlewis** [comment]
Hi,

Does this happen when you're searching:

* the inbox using `.i`
* all tasks using `.s`

Cheers,
Rhyd

**Comment by macfreek** [comment]
My bug report This happens when I'm using `.s`.
My apologies for not mentioning that.

If I use `.i`, it uses another query, and does find items in the inbox.

Is it intended that items in the inbox are not shown with `.s`? I expected them to be shown.

**Comment by rhydlewis** [comment]
For the way I use OmniFocus, `.s` only searches processed tasks/projects whereas `.i` is for searching tasks within the Inbox. I keep the Inbox separate because I've not thought about what the contents mean yet.

Doesn't mean that my way is the only way though. Let me have a think about another query (maybe `.se`for search everything) that drops the ignore inbox clause. Would that work for you?

**Comment by macfreek** [comment]
That would indeed work for me.

I'm aware that while I use OF, I'm not very well versed in GTD :).  (I.e. significantly more is getting in that what I can possibly do). The ability to quickly check if I have already entered or classified a particular taks is of help to me. That means a quick search in both inbox and projects helps me make that check.

**Comment by rhydlewis** [comment]
Fixed in v1.2.3.

**Comment by macfreek** [comment]
Thanks, works like a charm.
