### ISSUE TITLE
Upgrade alfred-workflow to latest

### ISSUE THREAD

**Issue by askedrelic** [rhydlewis/search-omnifocus#23]
I'm running into a 100% CPU hang from the alfred workflow update in this plugin, which looks like this bug https://github.com/deanishe/alfred-workflow/issues/111

It looks like 1.9 is the current version in this plugin https://github.com/rhydlewis/search-omnifocus/blob/master/workflow/update.py

And 1.26 is available https://github.com/deanishe/alfred-workflow/releases

I might try seeing if I can get a PR going...

**Comment by deanishe** [comment]
[This workflow](https://github.com/deanishe/alfred-fixum) provides a temporary fix for the bug until authors push official updates. It replaces all outdated versions of Alfred-Workflow in all installed workflows.
