### ISSUE TITLE
OmniFocus Unable to show linked item

### ISSUE THREAD

**Issue by cands** [rhydlewis/search-omnifocus#25]
Thanks for making this great workflow! For some time I've hade some issues with showing selected projects in OmniFocus.

Sometimes OmniFocus shows the message "Unable to show linked item: There is no item with the unique identifier given in the link." when I want to show the project found with the workflow. This affects only certain projects. I have not been able to track down any differences between the projects that can be shown in OmniFocus (this is the vast majority) and the ones that don't show up and generates the above error message (a minority of projects).

**Comment by rhydlewis** [comment]
Thanks for raising this. I'll investigate and get back to you.

**Comment by rhydlewis** [comment]
@cands are the tasks you're searching for repeating tasks? If you're able to run a query against your OF database I might be able to look at what's happening. Let me know and I can explain how to do it.

**Comment by cands** [comment]
Sorry for late reply. Yes, it does seem to affect only repeating tasks (I have not done extensive testing). Yes, I can run a query if you give instructions how to do it. Thanks you very much for investigating.

**Comment by rhydlewis** [comment]
@cands sorry for my late reply... Is this problem still happening?

**Comment by cands** [comment]
No - I just updated to the latest version 1.2.7 of the workflow, and the issue seems to be sorted out now (I haven't done extensive tests). I'll let you know if I experience the issue again.
