### ISSUE TITLE
Searching for projects starting with Swedish characters does not work as intended

### ISSUE THREAD

**Issue by cands** [rhydlewis/search-omnifocus#26]
The workflow is unable to find projects whose name starts with the Swedish character "Å", e.g. if I search for "årsvis" the project "Årsvis..." does not show up. However, the project is found if I enter upper case "Å", i.e. I search for "Årsvis".

**Comment by deanishe** [comment]
Sounds like a duplicate of #19

**Comment by cands** [comment]
Yes, you're right it's a duplicate! Sorry for not having checked if it was previously reported.

**Comment by deanishe** [comment]
Depending on how many projects/contexts people have, it might be possible to also filter those in Python, so non-ASCII works, too.
