### ISSUE TITLE
[Feauture request] Allow completing/flagging tasks when they are actioned with some modifier

### ISSUE THREAD

**Issue by Stvad** [rhydlewis/search-omnifocus#27]
It would be great if I could complete the task by actioning it with Cmd modifier for example.

**Comment by rhydlewis** [comment]
v1.2.5 supports this - cheers.

https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.2.5

**Comment by rhydlewis** [comment]
Well, it supports closing a task but not flagging it.

**Comment by rhydlewis** [comment]
v1.2.6 supports flagging/un-flagging - cheers!

https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.2.6

**Comment by Stvad** [comment]
Great, thank you!
