### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by rootion** [rhydlewis/search-omnifocus#31]
- Workflow release v2.0.0
- Alfred 3
- Omnifocus 2

When performing any search, such as `.sa buy` or `.s buy` Alfred will display the following error: `Unable to open database file`. 

Is this release incompatible with Omnifocus 2? I don't really see what other issue could be.

**Comment by rhydlewis** [comment]
Hi, please install [version v1.2.7](https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.2.7). v2.0.0 is a pre-release with initial support for OmniFocus 3.

Thanks
