### ISSUE TITLE
Error "unable to open database file"

### ISSUE THREAD

**Issue by johnchidiac** [rhydlewis/search-omnifocus#32]
Since I've upgraded to OmniFocus 3, I get an error "unable to open database file" when searching with this workflow.

**Comment by rhydlewis** [comment]
Hi John,

Updating the workflow to the [latest release](
https://github.com/rhydlewis/search-omnifocus/releases/tag/v2.0.2) should allow you to use OmniFocus 3. You'll need to tell the workflow to use v3 by using the Alfred keyword `use-of-3` then you should be ready to go.

Cheers,
Rhyd

**Comment by rhydlewis** [comment]
Awesome :)
