### ISSUE TITLE
In the release version 2.0.3, 'version' is still tagged as 2.0.2

### ISSUE THREAD

**Issue by askedrelic** [rhydlewis/search-omnifocus#33]
I just updated OF3 and found I need to update my workflow. I'm so glad you have kept updating this workflow!

I downloaded the 2.0.3 release from github, but when using this version inside Alfred, the alfred "workflow update" plugin thing kept popping up.

It looks like in the 2.0.3 binary, the 'version' file is still tagged as 2.0.2. Did something get messed up during upload? Maybe just doublecheck that I'm not crazy?
https://github.com/rhydlewis/search-omnifocus/releases/download/v2.0.3/Search.OmniFocus.v2.0.3.alfredworkflow

**Comment by rhydlewis** [comment]
Ach! Yes, you're right. Sorry about that. I've updated the [release to 2.0.4](https://github.com/rhydlewis/search-omnifocus/releases/tag/v2.0.4) so hopefully that'll fix it.

**Comment by askedrelic** [comment]
Thanks! The new release looks correct to me. Cheers!
