### ISSUE TITLE
Does it support Alfred 4?

### ISSUE THREAD

**Issue by jakob-lewei** [rhydlewis/search-omnifocus#39]
![image](https://user-images.githubusercontent.com/37611866/58923270-8b526d80-8771-11e9-9be6-fbe9f126416e.png)

**Comment by rhydlewis** [comment]
Hi Jakob,

It does for me. I migrated my settings from Alfred 3 to Alfred 4 and it works without any errors. Can you share your workflow log file so I can look at why this isn't working for you? Example below.

![Screenshot 2019-06-05 at 06 16 03](https://user-images.githubusercontent.com/2102276/58931938-96010880-8759-11e9-8e86-19f6c813f528.png)

Cheers,
Rhyd

**Comment by jakob-lewei** [comment]
yes it works. I need to switch to of3 by entering 
```
use-of-3
```

**Comment by rhydlewis** [comment]
Ok - thanks for letting me know
