### ISSUE TITLE
Incompatible in Alfred v3.8.2

### ISSUE THREAD

**Issue by sktoozaki** [rhydlewis/search-omnifocus#41]
Hi,

I installed Search.OmniFocus.v2.0.6.alfredworkflow and found Alfred shows "Workflow Incompatible.Please update to the latest version of Alfred", but it is the latest version.

**Comment by rhydlewis** [comment]
Which version of Alfred are you running?

**Comment by sktoozaki** [comment]
v3.8.2[963]

**Comment by jt-z** [comment]
I met the same issue,and the version of my alfred is v3.8 too.Actually,now the latest version is [Alfred 4](https://www.alfredapp.com/).Perhaps,this workflow need work with the latest version.

**Comment by rhydlewis** [comment]
The workflow is ok for me on Alfred 3 and 4. Can you send me your debug log from Alfred after running the workflow and I’ll take a look. Thanks

**Comment by jt-z** [comment]
Thanks for your reply. It just show this follow information: _""Workflow Incompatible.Please update to the latest version of Alfred.""_
This is the original error page picture: [https://ws4.sinaimg.cn/large/006tNc79ly1g5qewukhjoj30qc07v74o.jpg](url)

**Comment by rhydlewis** [comment]
The problem is that I exported the latest version of the workflow using Alfred 4 which means it doesn't work with Alfred 3. I'll create a version that works with v3 soon.

**Comment by rhydlewis** [comment]
@jt-z @sktoozaki Please try this version https://github.com/rhydlewis/search-omnifocus/releases/download/v2.0.6/Search.OmniFocus.v2.0.6.Alfred3.alfredworkflow

**Comment by jt-z** [comment]
> @jt-z @sktoozaki Please try this version https://github.com/rhydlewis/search-omnifocus/releases/download/v2.0.6/Search.OmniFocus.v2.0.6.Alfred3.alfredworkflow

Thank you! It works after I import this workflow.

**Comment by xevilgenius** [comment]
> @jt-z @sktoozaki Please try this version https://github.com/rhydlewis/search-omnifocus/releases/download/v2.0.6/Search.OmniFocus.v2.0.6.Alfred3.alfredworkflow

Cannot appreciate more:)
