### ISSUE TITLE
Workflow doesn't show results from OmniFocus after upgrade to 3.5

### ISSUE THREAD

**Issue by rhydlewis** [rhydlewis/search-omnifocus#42]
## Problem

After upgrading to OmniFocus 3.5, my OmniFocus database moved from:

`/Library/Containers/com.omnigroup.OmniFocus3/Data/Library/Application Support/OmniFocus/OmniFocus Caches/OmniFocusDatabase` / `/Library/Containers/com.omnigroup.OmniFocus3.MacAppStore/Data/Library/Application Support/OmniFocus/OmniFocus Caches/OmniFocusDatabase`

to:

`/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db` /
`/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3.MacAppStore/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db`

~The `34YW5XSRB7` looks randomly/uniquely generated so will need to think about how to solve this.~
`34YW5XSRB7` is OmniGroup's container/team ID - think it's safe to assume this will be the same for everyone

## Impact

Search OmniFocus workflow continues to show results from OmniFocus created before upgrading but nothing added or changed after upgrading.

## Workaround

**OmniFocus Database**

1. Open Terminal
2. `find ~/Library/Group\ Containers/ -name "OmniFocusDatabase.db"`
3. Copy result from /Library onwards

**Workflow**
1. Open Alfred Preferences
2. Right click on Search Omnifocus workflow and choose open in Finder
3. Open `search.py` in a text editor
4. Add a # to start of line 21 `OF3_DB_LOCATION=...`
5. Add new line after line 21:

`OF3_DB_LOCATION = "<text you copied above 👆>"`

6. Save file. Test workflow finds information entered after you upgraded to 3.5.

**Comment by cands** [comment]
Thank you, this solved the issue for me as well!

**Comment by rhydlewis** [comment]
Fixed by version 2.1.0
