### ISSUE TITLE
v2.1.1 is no longer support Alfred 3?

### ISSUE THREAD

**Issue by CalanceHao** [rhydlewis/search-omnifocus#45]
macOS Catalina v10.15.4
Alfred 3.8.6[972]

After the update, this workflow is not worked.
"Workflow incompatible. Please update to the latest version of Alfred. "

 I have tried: v2.1.1 2.1.0 2.0.5
They show the same message……

Could you tell me which version can be used on Alfred 3.8.6[972]?
OR is there any problem??? Cause you didn't say Alfred 3 is never supported on release log.

**Comment by rhydlewis** [comment]
Please try v2.0.6 (last version built for Alfred 3) which is [available here](https://github.com/rhydlewis/search-omnifocus/releases/download/v2.0.6/Search.OmniFocus.v2.0.6.Alfred3.alfredworkflow).

**Comment by CalanceHao** [comment]
↖(^ω^)↗ Yes~ It works~ THX:)
