### ISSUE TITLE
.d does not work with the latest Omnifocus and Alfred

### ISSUE THREAD

**Issue by minjaep** [rhydlewis/search-omnifocus#47]
VERSION_KEY='of_version' does not work, so I removed version checking to make it work.

Also line 102 of factory.py should add "Z" like:
            due_date = parse_datetime(row[DUE_DATE]+"Z")

**Comment by rhydlewis** [comment]
The `.d` option works for me - what problem are you seeing? Can you share your Alfred Workflow logs?

**Comment by lescude** [comment]
Thanks for the quick response!  I hope to become proficient with python like yourself some day!!! I zipped the directory of the workflow and attached it. 

Thanks in advance for taking time out to look at this. 
[Archive.zip](https://github.com/rhydlewis/search-omnifocus/files/5117481/Archive.zip)


<img width="574" alt="Screen Shot 2020-08-24 at 7 32 38 AM" src="https://user-images.githubusercontent.com/42253766/91040312-ff2d9f80-e5db-11ea-8826-5e9a86db6240.png">

**Comment by rhydlewis** [comment]
Yes, spotted the issue. I'll have a fix out soon.

**Comment by rhydlewis** [comment]
See if this [release](https://github.com/rhydlewis/search-omnifocus/releases/tag/2.1.2) works

**Comment by lescude** [comment]
Awesome!!!! Thanks for taking the time to create and develop this.
