### ISSUE TITLE
List inbox (.li) also shows completed items.

### ISSUE THREAD

**Issue by patowod** [rhydlewis/search-omnifocus#48]
Hi, great workflow — thanks for making it :) This really makes OF much more accessible! I just installed it and noticed what the title says: listing inbox items also show completed items. A quick solution for this is to use "File > Move old data to archive" which resolves the issue if you then actually move the data… I didn't even know that this option existed so I wanted to let you know about the issue, and anyone else that there is a quick workaround. 

Thanks again for this awesome workflow!

**Comment by rhydlewis** [comment]
No problem! Thanks for the tip 👍
