### ISSUE TITLE
Doesn't find tasks with subtasks (or project folders)

### ISSUE THREAD

**Issue by deanishe** [rhydlewis/search-omnifocus#5]
I organise a lot of my tasks like this:

- Parent task
    - Subtask 1
    - Subtask 2
    - Subtask 3

When searching tasks with `.s <query>`, "Parent task" doesn't show up in the results. All subtasks are there, however. I like to navigate straight to "Parent task", as the subtasks are often obscure things like document names that I can't remember.

Similarly, project folders don't show up anywhere in the results, but that's not a huge deal as, unlike a lot of my tasks, I can remember project names.

**Comment by rhydlewis** [comment]
Will look at this - cheers

**Comment by rhydlewis** [comment]
Should be fixed in [v1.1.6](https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.1.6)

**Comment by rhydlewis** [comment]
That is, searching for parent tasks now works. Searching for project folders isn't something I've considered.

**Comment by deanishe** [comment]
:+1: Great work. I bloody love this workflow. So fast.
