### ISSUE TITLE
Show a "no results" message when there are no results?

### ISSUE THREAD

**Issue by deanishe** [rhydlewis/search-omnifocus#6]
This is very much a personal preference, but I dislike being dropped into Alfred's fallback searches when using a workflow. Mostly because it's hard to tell if that means there are no results or that the workflow crashed.

Would you consider showing a "No matching results" item when there are no results?

**Comment by rhydlewis** [comment]
Yep, sounds like a good idea.

**Comment by rhydlewis** [comment]
Should be fixed in [v1.1.6](https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.1.6)
