### ISSUE TITLE
Getting "No Items" more often then not

### ISSUE THREAD

**Issue by broderboy** [rhydlewis/search-omnifocus#7]
The base search isn't finding many of my tasks.
What other info can I provide to help debug?

Thanks

<img width="1262" alt="2015-08-23_1208" src="https://cloud.githubusercontent.com/assets/121503/9429011/d0353884-498f-11e5-98dd-3f8ae67c04d3.png">

**Comment by rhydlewis** [comment]
Hmm, sorry to hear that. Can you do the following?

* Show Alfred preferences (keyword 'alf')
* Click 'Workflows' in the tool bar
* Choose 'Search Omnifocus' from the list of workflows on the left
* Click on the 'Debug' to toggle debugging mode (see [Alfred's help page for more info](https://www.alfredapp.com/help/workflows/advanced/debugger/))
* Choose 'All information' from the Log dropdown
* Open Alfred and type '.s Hum'
* Copy the debug output and post it as a response - I'll take a look.

Cheers

**Comment by broderboy** [comment]
Sure, Thanks!

https://gist.github.com/broderboy/066bf6dcce47e138fd7b/

**Comment by rhydlewis** [comment]
Do you have the Mac AppStore version or did you buy Omnifocus direct from Omnigroup? I'm wondering whether there is an older database stored in the non-Mac App Store location which means the workflow isn't using a more up to date version.

Can you run the following 2 commands and send me the results?

    ls -la /Users/tbroder/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Caches/com.omnigroup.OmniFocus2/OmniFocusDatabase2
    ls -la /Users/tbroder/Library/Containers/com.omnigroup.OmniFocus2.MacAppStore/Data/Library/Caches/com.omnigroup.OmniFocus2.MacAppStore/OmniFocusDatabase2

**Comment by broderboy** [comment]
I bought in the MAS

https://gist.githubusercontent.com/broderboy/eaab4c6dedeb61c29045/

Thanks

**Comment by rhydlewis** [comment]
Try [this release](https://github.com/rhydlewis/search-omnifocus/releases/tag/v1.1.9). It checks if an older, non-Mac AppStore database exists and then switches to the newer, MAS version instead. Let me know if it works.

**Comment by broderboy** [comment]
Working perfectly! Thanks!!
